[build]
  publish = "public"
  command = "node scripts/write-config.js"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "microphone=(self)"
